// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/dispatcher.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DispatchMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchMessageRequest) Reset() {
	*x = DispatchMessageRequest{}
	mi := &file_proto_dispatcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchMessageRequest) ProtoMessage() {}

func (x *DispatchMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchMessageRequest.ProtoReflect.Descriptor instead.
func (*DispatchMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_dispatcher_proto_rawDescGZIP(), []int{0}
}

func (x *DispatchMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DispatchMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DispatchMessageRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *DispatchMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DispatchMessageRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type DispatchMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Successful    bool                   `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchMessageResponse) Reset() {
	*x = DispatchMessageResponse{}
	mi := &file_proto_dispatcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchMessageResponse) ProtoMessage() {}

func (x *DispatchMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchMessageResponse.ProtoReflect.Descriptor instead.
func (*DispatchMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_dispatcher_proto_rawDescGZIP(), []int{1}
}

func (x *DispatchMessageResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

var File_proto_dispatcher_proto protoreflect.FileDescriptor

const file_proto_dispatcher_proto_rawDesc = "" +
	"\n" +
	"\x16proto/dispatcher.proto\x12\n" +
	"dispatcher\"\xa8\x01\n" +
	"\x16DispatchMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tR\tchannelId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"9\n" +
	"\x17DispatchMessageResponse\x12\x1e\n" +
	"\n" +
	"successful\x18\x01 \x01(\bR\n" +
	"successful2h\n" +
	"\n" +
	"Dispatcher\x12Z\n" +
	"\x0fDispatchMessage\x12\".dispatcher.DispatchMessageRequest\x1a#.dispatcher.DispatchMessageResponseB\x0fZ\rdispatcher/pbb\x06proto3"

var (
	file_proto_dispatcher_proto_rawDescOnce sync.Once
	file_proto_dispatcher_proto_rawDescData []byte
)

func file_proto_dispatcher_proto_rawDescGZIP() []byte {
	file_proto_dispatcher_proto_rawDescOnce.Do(func() {
		file_proto_dispatcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dispatcher_proto_rawDesc), len(file_proto_dispatcher_proto_rawDesc)))
	})
	return file_proto_dispatcher_proto_rawDescData
}

var file_proto_dispatcher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_dispatcher_proto_goTypes = []any{
	(*DispatchMessageRequest)(nil),  // 0: dispatcher.DispatchMessageRequest
	(*DispatchMessageResponse)(nil), // 1: dispatcher.DispatchMessageResponse
}
var file_proto_dispatcher_proto_depIdxs = []int32{
	0, // 0: dispatcher.Dispatcher.DispatchMessage:input_type -> dispatcher.DispatchMessageRequest
	1, // 1: dispatcher.Dispatcher.DispatchMessage:output_type -> dispatcher.DispatchMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_dispatcher_proto_init() }
func file_proto_dispatcher_proto_init() {
	if File_proto_dispatcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dispatcher_proto_rawDesc), len(file_proto_dispatcher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dispatcher_proto_goTypes,
		DependencyIndexes: file_proto_dispatcher_proto_depIdxs,
		MessageInfos:      file_proto_dispatcher_proto_msgTypes,
	}.Build()
	File_proto_dispatcher_proto = out.File
	file_proto_dispatcher_proto_goTypes = nil
	file_proto_dispatcher_proto_depIdxs = nil
}
