// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/channel_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelRequest) Reset() {
	*x = CreateChannelRequest{}
	mi := &file_proto_channel_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelRequest) ProtoMessage() {}

func (x *CreateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_channel_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelRequest.ProtoReflect.Descriptor instead.
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return file_proto_channel_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelResponse) Reset() {
	*x = CreateChannelResponse{}
	mi := &file_proto_channel_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelResponse) ProtoMessage() {}

func (x *CreateChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_channel_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelResponse.ProtoReflect.Descriptor instead.
func (*CreateChannelResponse) Descriptor() ([]byte, []int) {
	return file_proto_channel_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChannelResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateChannelResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListChannelDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelDetailRequest) Reset() {
	*x = ListChannelDetailRequest{}
	mi := &file_proto_channel_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelDetailRequest) ProtoMessage() {}

func (x *ListChannelDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_channel_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelDetailRequest.ProtoReflect.Descriptor instead.
func (*ListChannelDetailRequest) Descriptor() ([]byte, []int) {
	return file_proto_channel_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListChannelDetailRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ChannelMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JoinedAt      int64                  `protobuf:"varint,2,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelMember) Reset() {
	*x = ChannelMember{}
	mi := &file_proto_channel_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelMember) ProtoMessage() {}

func (x *ChannelMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_channel_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelMember.ProtoReflect.Descriptor instead.
func (*ChannelMember) Descriptor() ([]byte, []int) {
	return file_proto_channel_service_proto_rawDescGZIP(), []int{3}
}

func (x *ChannelMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChannelMember) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

type ChannelDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Members       []*ChannelMember       `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelDetail) Reset() {
	*x = ChannelDetail{}
	mi := &file_proto_channel_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelDetail) ProtoMessage() {}

func (x *ChannelDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_channel_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelDetail.ProtoReflect.Descriptor instead.
func (*ChannelDetail) Descriptor() ([]byte, []int) {
	return file_proto_channel_service_proto_rawDescGZIP(), []int{4}
}

func (x *ChannelDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChannelDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelDetail) GetMembers() []*ChannelMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type ListChannelDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*ChannelDetail       `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelDetailResponse) Reset() {
	*x = ListChannelDetailResponse{}
	mi := &file_proto_channel_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelDetailResponse) ProtoMessage() {}

func (x *ListChannelDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_channel_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelDetailResponse.ProtoReflect.Descriptor instead.
func (*ListChannelDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_channel_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListChannelDetailResponse) GetChannels() []*ChannelDetail {
	if x != nil {
		return x.Channels
	}
	return nil
}

type JoinChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinChannelRequest) Reset() {
	*x = JoinChannelRequest{}
	mi := &file_proto_channel_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChannelRequest) ProtoMessage() {}

func (x *JoinChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_channel_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChannelRequest.ProtoReflect.Descriptor instead.
func (*JoinChannelRequest) Descriptor() ([]byte, []int) {
	return file_proto_channel_service_proto_rawDescGZIP(), []int{6}
}

func (x *JoinChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *JoinChannelRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type JoinChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinChannelResponse) Reset() {
	*x = JoinChannelResponse{}
	mi := &file_proto_channel_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChannelResponse) ProtoMessage() {}

func (x *JoinChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_channel_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChannelResponse.ProtoReflect.Descriptor instead.
func (*JoinChannelResponse) Descriptor() ([]byte, []int) {
	return file_proto_channel_service_proto_rawDescGZIP(), []int{7}
}

func (x *JoinChannelResponse) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *JoinChannelResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_proto_channel_service_proto protoreflect.FileDescriptor

const file_proto_channel_service_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/channel_service.proto\x12\x0fchannel_service\"*\n" +
	"\x14CreateChannelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\";\n" +
	"\x15CreateChannelResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"3\n" +
	"\x18ListChannelDetailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"E\n" +
	"\rChannelMember\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tjoined_at\x18\x02 \x01(\x03R\bjoinedAt\"m\n" +
	"\rChannelDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x128\n" +
	"\amembers\x18\x03 \x03(\v2\x1e.channel_service.ChannelMemberR\amembers\"W\n" +
	"\x19ListChannelDetailResponse\x12:\n" +
	"\bchannels\x18\x01 \x03(\v2\x1e.channel_service.ChannelDetailR\bchannels\"L\n" +
	"\x12JoinChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"M\n" +
	"\x13JoinChannelResponse\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId2\xb7\x02\n" +
	"\x0eChannelService\x12^\n" +
	"\rCreateChannel\x12%.channel_service.CreateChannelRequest\x1a&.channel_service.CreateChannelResponse\x12k\n" +
	"\x12ListChannelDetails\x12).channel_service.ListChannelDetailRequest\x1a*.channel_service.ListChannelDetailResponse\x12X\n" +
	"\vJoinChannel\x12#.channel_service.JoinChannelRequest\x1a$.channel_service.JoinChannelResponseB\x14Z\x12channel-service/pbb\x06proto3"

var (
	file_proto_channel_service_proto_rawDescOnce sync.Once
	file_proto_channel_service_proto_rawDescData []byte
)

func file_proto_channel_service_proto_rawDescGZIP() []byte {
	file_proto_channel_service_proto_rawDescOnce.Do(func() {
		file_proto_channel_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_channel_service_proto_rawDesc), len(file_proto_channel_service_proto_rawDesc)))
	})
	return file_proto_channel_service_proto_rawDescData
}

var file_proto_channel_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_channel_service_proto_goTypes = []any{
	(*CreateChannelRequest)(nil),      // 0: channel_service.CreateChannelRequest
	(*CreateChannelResponse)(nil),     // 1: channel_service.CreateChannelResponse
	(*ListChannelDetailRequest)(nil),  // 2: channel_service.ListChannelDetailRequest
	(*ChannelMember)(nil),             // 3: channel_service.ChannelMember
	(*ChannelDetail)(nil),             // 4: channel_service.ChannelDetail
	(*ListChannelDetailResponse)(nil), // 5: channel_service.ListChannelDetailResponse
	(*JoinChannelRequest)(nil),        // 6: channel_service.JoinChannelRequest
	(*JoinChannelResponse)(nil),       // 7: channel_service.JoinChannelResponse
}
var file_proto_channel_service_proto_depIdxs = []int32{
	3, // 0: channel_service.ChannelDetail.members:type_name -> channel_service.ChannelMember
	4, // 1: channel_service.ListChannelDetailResponse.channels:type_name -> channel_service.ChannelDetail
	0, // 2: channel_service.ChannelService.CreateChannel:input_type -> channel_service.CreateChannelRequest
	2, // 3: channel_service.ChannelService.ListChannelDetails:input_type -> channel_service.ListChannelDetailRequest
	6, // 4: channel_service.ChannelService.JoinChannel:input_type -> channel_service.JoinChannelRequest
	1, // 5: channel_service.ChannelService.CreateChannel:output_type -> channel_service.CreateChannelResponse
	5, // 6: channel_service.ChannelService.ListChannelDetails:output_type -> channel_service.ListChannelDetailResponse
	7, // 7: channel_service.ChannelService.JoinChannel:output_type -> channel_service.JoinChannelResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_channel_service_proto_init() }
func file_proto_channel_service_proto_init() {
	if File_proto_channel_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_channel_service_proto_rawDesc), len(file_proto_channel_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_channel_service_proto_goTypes,
		DependencyIndexes: file_proto_channel_service_proto_depIdxs,
		MessageInfos:      file_proto_channel_service_proto_msgTypes,
	}.Build()
	File_proto_channel_service_proto = out.File
	file_proto_channel_service_proto_goTypes = nil
	file_proto_channel_service_proto_depIdxs = nil
}
